name: 'Release'
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string

jobs:
  release:
    name: 'Release'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v3

      - name: 'GitHub Release'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ inputs.tag }}
          prerelease: false
          title: ${{ inputs.tag }}

      - name: 'Close Milestone'
        uses: Akkjon/close-milestone@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          milestone_name: ${{ inputs.tag }}
